name = "Weapons-Balance-GM"
prefix = "wb_gm"
author = "johnb43"
template = "cba"
mainprefix = "z"
files = [
    "CHANGELOG.md",
    "mod.cpp",
    "LICENSE"
]
folder_optionals = false
sig_version = 3
